[unstable]
mtime-on-use = true
build-std = ["core", "alloc", "panic_abort","compiler_builtins"]
build-std-features = ["compiler-builtins-mem","panic_immediate_abort"]

[build]
target = "x86_64-pc-windows-msvc"
rustflags = ["-Clink-args=/MAP"]